#!/usr/bin/env bash

#--------------------------------------------------------------------------------------------------#
# Cluster settings
#   dev-rook-ceph uses https://github.com/galexrt/k8s-vagrant-multi-node to stand up Kubernetes
#   clusters. Refer to those docs for more settings that can be used to configure the cluster.
#--------------------------------------------------------------------------------------------------#

export NODE_COUNT=0

export MASTER_CPUS=6
export MASTER_MEMORY_SIZE_GB=6

export DISK_COUNT=6
export DISK_SIZE_GB=10
