#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${SCRIPT_DIR}/_default-dev-settings"

# Add your own overrides to the default-dev-settings here
# examples:
# export K8S_VERSION="v1.12.4"
# export CLUSTER_PREFIX=""
# export LIBVIRT_OS_VOL_POOL="ssd"
