#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=_default-dev-settings
source "${SCRIPT_DIR}/_default-dev-settings"

# Add your own overrides to the default-dev-settings here
# examples:

# export NODE_COUNT=3

# export NODE_CPUS=2
# export NODE_MEMORY_GB=4

# export NODE_DISK_COUNT=1
# export NODE_DISK_SIZE_GB=20
